baseurl = "/"
languageCode = "en-uk"
theme = "hello-friend-ng"
disqusShortname = "matishadow-blog"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Security stuff by matishadow"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Security and programming stuff"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "matishadow's blog"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "polish-blog"
        name = "Polish blog"
        url = "https://majtkishadow-blog.gear.host/"
